# -*- coding: utf-8 -*-
"""Client.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xcDkXGxQk6k62FG4idVipXBK2QQ_KRYW
"""

#Client Code
import socket

# take the server name and port name
host = 'local host'
#host = socket.gethostname()
port = 5000
  
# create a socket at client side
# using TCP / IP protocol
s = socket.socket(socket.AF_INET,
                  socket.SOCK_STREAM)
  
# connect it to server and port
# number on local computer.
s.connect(('192.168.0.139', port))
#s.connect((host, port))
  
# receive message string from
# server, at a time 1024 
msg = s.recv(1024)
 
# repeat as long as message
# string are not empty

while msg:
    msg1 = msg.decode()
    print('Received:' + msg1)
    if msg1[0] == '0':
      destination = msg1[1:]
      print(destination)
    else:
      print("Destination not found")

    if msg1 == destination: 
      print("Destination is reached!")
      break
    else:
      print("Destination is not reached!")
      break
 
# disconnect the client
s.close()
